### ISSUE TITLE
Nest Common Struct in API file 

### ISSUE THREAD

**Issue by waltcow** [arklnk/ark-admin-zero#16]
There are many repeated struct types in api files, like `XxxPagination`, maybe we can nested it in its parent struct,  with this feature support [generates nested types in doc](https://github.com/zeromicro/go-zero/pull/2201)

**Comment by Trevor-Lan** [comment]
[refactor: add common.api and add label field](https://github.com/arklnk/ark-admin-zero/commit/c3586763dcb30ecf8cf1ec3c6b89a4c1743ac0b2)
