### ISSUE TITLE
api文件中prefix : /admin/user， 但是postman请求时必须是 /api/admin/user

### ISSUE THREAD

**Issue by chemwol** [arklnk/ark-admin-zero#27]
api文件中prefix : /admin/user， 但是postman请求时必须是 /api/admin/user  ， 不太明白为什么会出现这种情况，能解答一下吗

**Comment by Trevor-Lan** [comment]
那是因为前端部署时加了api前缀，这样可以隐藏真实的后端api地址，可以根据自己项目情况修改api前缀。
![image](https://github.com/arklnk/ark-admin-zero/assets/61399914/c3533f41-1301-4572-907c-f0e31b740464)

**Comment by chemwol** [comment]
我的意思没有使用nginx的情况下，本地运行调试时，请求路由也必须像这样：/api/admin/user 带上/api，但是api文件中prefix : /admin/user， 这当中就多出来一个api，不清楚是在哪里定义的

**Comment by Trevor-Lan** [comment]
docker环境本地运行调试，直接走后端服务是不用api前缀的，你可以查看下调试的api的端口，80端口是走前端代理的（需要api前缀），8000端口走nginx网关（不需要api前缀），或者自己把api服务的端口暴露出来，直接走api服务端口也是不需要api前缀的。详细可以查看docker-compose配置文件。
![image](https://github.com/arklnk/ark-admin-zero/assets/61399914/21314a7f-2155-4113-9460-3f148edb9cfd)

**Comment by chemwol** [comment]
感谢回答，这次终于弄明白了，是我这边nginx配置导致的
